apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{.Values.scale}} 
  template: 
    metadata:
      labels:
        app: nginx
        site: USA
        deployment: production
    spec:
      containers: 
      - name: nginx 
        image: nginx:{{.Values.tag}}
        ports: 
        - containerPort: 80
 
